### PR TITLE
add Vietnamese characters with 2 diacritics

### PR DESCRIPTION
**Pull request by nlhkh**
There are Vietnamese characters with 2 diacritics (1 diacritic as part of a letter, 1 diacritic as a phonic modifier). Without these, `UNACCENT` simply ignores these letters with 2 diacritics.

### CODE REVIEW

**Comment by seiji619** [comment]
You can submit the patch to their official git repo - this GitHub repo is just the mirror of that repo.

**Comment by rohmanhm** [comment]
http://wiki.postgresql.org/wiki/Submitting_a_Patch

**Comment by nlhkh** [comment]
Could you provide me with more information on how to submit a patch?
I get as far as sending a patch to the email ` pgsql-hackers@postgresql.org`, but how can I create a patch?

**Comment by nlhkh** [comment]
Is it simply sending the output of `git diff` to the hackers email?

**Comment by alasdairdc** [comment]
heres a [link to someone elses patch](https://www.postgresql.org/message-id/89ba433e-8990-0aad-238f-55e1d7280ece%402ndquadrant.com) on `pgsql-hackers`

**Pull request closed without merging**
